### ISSUE TITLE
Vulnerability Report: Path traversal and Code Execution in dlopen via environment variable

### ISSUE THREAD

**Issue by cldrn** [smowton/vgallium#2]
### Vulnerability Report: Path traversal and Code Execution in dlopen via environment variable

Affected Project & Line:
https://github.com/smowton/vgallium/blob/d4491936ef449c8da1225285e02bd1f3e91668bd/src/src/glx/x11/dri_glx.c#L248

#### Summary
Applications using XXX may be vulnerable to attacks where a local attacker could execute arbitrary code through a maliciously crafted library, loaded via the dlopen() function. This could potentially lead to privilege escalation.

#### Details
The application reads unsanitized data from the environment variable. This tainted path is subsequently used directly by dlopen() without sufficient validation, allowing directory traversal and possibly loading external malicious libraries.

The security check currently implemented using [specific security check, e.g., geteuid() == getuid()] does not adequately protect against this vulnerability.

#### Reproduction Steps
	1. Set the affected environment variable to a path containing a maliciously crafted library.
	2. Run the application or initiate the specific function that calls dlopen().
	3. Observe that the malicious code within the library gets executed.

#### Impact
Attackers with local access can load and execute arbitrary code in systems using the affected application. This can lead to data corruption, data theft, and potentially complete system compromise depending on the application's privileges.

#### Recommendation
	• Implement thorough input validation for the paths loaded via the environment variables.
	• Use a whitelist of allowed paths or directory names to mitigate the risk of arbitrary directory traversal.
	• Drop elevated privileges immediately after they are no longer required.
	• Regularly audit and review the code to ensure that all paths from which libraries or other external resources are loaded are properly validated.
	• Check and compare the real group ID and the effective group ID with getgid() and getegid()

#### CVSS Score
High 7.8 [CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H]

#### Root Cause Analysis
The root cause of this vulnerability stems from the lack of input validation when reading paths from environment variables and the subsequent insecure use of such paths with the dlopen() function.

### Additional References
https://docs.google.com/document/d/1lRE2lc00WAYa-427crBFO1yBzU7fSUmQIanh9W8Rglo/edit?usp=sharing

**Comment by smowton** [comment]
Closing because:

1. This looks like an unsubstituted template issue? ("Applications using XXX")
2. The cited line doesn't contain either a dlopen call or environment variable reference, so at least something is broken with the bot generating these
3. The code complained about is from GLX
4. GLX opens a library specified by an environment variable by design

**Comment by cldrn** [comment]
1. Yes, the XXX is an error in this one. I had to use a template as I am reporting a similar issue in over 50 projects.
2. The problem lies with the comparison L248 is pointing to. Please refer to the blog post in the additional references section for more examples and details on why this security check is insufficient.
3. Yes, the code is included in this project though.
4. The problem is the security check where group permissions are not considered. It prevents loading DLLs with different user perms but not groups. Please refer to the post I attached at the end.

**Comment by smowton** [comment]
I see. In that case I suggest changing the title of the vulnerability, since "Path traversal and Code Execution in dlopen via environment variable" strongly suggests you're complaining about not having sanitized the environment variable by comparing it against known-good values, checking it refers to a library within a particular directory, etc. I'd stopped reading by the third paragraph that actually clarifies we're talking about something completely different, an inadequate guard against privilege escalation. Perhaps "Checking effective uid but not effective gid may allow privilege escalation"?

Anyway, I've applied the suggested patch at https://github.com/smowton/vgallium/commit/3ecd6580244bdab19b23658ee9569c062edd9563. This is almost certainly pointless since this is 15-year-old almost-certainly-dead academic software, but you might want to chase after the real Mesa3D, which appears to use the same check today at https://github.com/Mesa3D/mesa/blob/main/src/loader/loader.c#L643
